### ISSUE TITLE
Mirror: no end-of-response framing, so clients never pipeline

### ISSUE THREAD

**Issue by lemenkov** [seerdb/seerdb#1059]
The 5 remaining `test_7600_pipelining_async.py` failures in #826 are a symptom.
The cause is that **the Mirror does not implement end-of-response framing**, so
python-oracledb never pipelines against it at all.

### Evidence

All 49 tests in that file **pass against a real 23ai** and 5 fail through the
Mirror, so it is ours. Capturing the same minimal pipeline against both:

| | real 23ai | Mirror |
|---|---|---|
| `BEGIN_PIPELINE` data flag (`0x1000`) | **1** | **0** |
| `END_OF_REQUEST` data flag (`0x0800`) | **1** | **0** |
| OALL8 calls per request packet | **2** (both ops in one packet) | 1 |

The real server answers that single 2-call packet with **two separate
responses**, each carrying its own `TTI_TOKEN` (33) correlation marker and
`TTI_END_OF_RESPONSE` (29). The Mirror gets no pipelined request to answer,
because the client never sends one.

Why the client does not: `handshake.py` deliberately leaves the ACCEPT `flags2`
word at zero, and says why —

> flags2 stays ZERO here even though a real 23ai sends `0x1A000000`. Those bits
> advertise FAST_AUTH (`0x10000000`) and end-of-response (`0x02000000`) … The
> Mirror emits no end-of-response markers, so claiming the bit would hang any
> client that believed it.

That is correct and still true: `grep TTI_END_OF_RESPONSE seerdb/server/`
returns nothing but a comment.

### Why it surfaces as a *fetch* bug

`run_pipeline` still works without the capability — the client falls back to
running the operations sequentially. But on that path it reads
`oracledb.defaults` at **run** time rather than the per-operation values
captured at **add** time, so a pipeline built inside a
`defaults_context_manager("fetch_decimals", True)` loses the setting by the time
it runs. Minimal repro, two `add_fetchone` on the same SQL differing only in
`fetch_decimals`:

```
real:    op[0] Decimal('7637')   op[1] 7637 (int)      <- per-op options honoured
mirror:  op[0] 7637 (int)        op[1] 7637 (int)      <- both take the run-time default
```

Hence `test_7637` / `7645` / `7646` (fetch_decimals) and `7647` / `7648`
(fetch_lobs). Nothing is wrong with the Mirror's number or LOB handling; the
options never reach the decode.

### Scope

- emit `TTI_END_OF_RESPONSE` (29) at the end of each response;
- emit the `TTI_TOKEN` (33) correlation marker the client matches responses by;
- read a request carrying several calls (`BEGIN_PIPELINE` / `END_OF_REQUEST`
  data flags) and answer each separately;
- advertise `0x02000000` in the ACCEPT `flags2`, which is safe only once the
  above hold — and only at a negotiated version >= 318, so an 11.2-identity
  Mirror still correctly says no;
- honour `TNS_PIPELINE_MODE_CONTINUE_ON_ERROR` vs `ABORT_ON_ERROR`.

The client half of this is #132 and already exists, so the constants and the
framing rules are known (`tns_consts.py`: `TNS_DATA_FLAGS_BEGIN_PIPELINE`,
`TNS_DATA_FLAGS_END_OF_REQUEST`, `TNS_DATA_FLAGS_END_OF_RESPONSE`,
`TTI_END_OF_RESPONSE`, `TTI_TOKEN`, `TNS_FUNC_PIPELINE_BEGIN` / `_END`).

### Note

The 44 other pipelining tests pass *because* the fallback is functionally
equivalent for them. That is worth knowing before anyone reads "44/49 pass" as
"pipelining mostly works" — none of them are pipelined at all.
